export const AUTO_LOCK_OPTIONS = [1, 5, 15, 30];
export const DEFAULT_AUTO_LOCK_MINUTES = 15;
export const STORAGE_KEYS = ["version", "salt", "auth", "vault", "settings", "meta"];
export const FOLDER_CATALOG_STORAGE_KEY = "folderCatalog";
export const PENDING_QUICK_CAPTURES_STORAGE_KEY = "pendingQuickCaptures";
export const SESSION_STORAGE_KEY = "safeMarksSession";
export const AUTO_LOCK_ALARM = "safeMarks-auto-lock";
export const VERSION = 1;
export const AUTH_SENTINEL = "SAFEMARKS_AUTH_V1";
